#+title: Logika - notatka pomocnicza do ćwiczeń (2024/2025)
#+AUTHOR: J. Szczerbowski
#+OPTIONS: tex:t p:t
#+LANGUAGE: pl
#+STARTUP: latexpreview

* Zajęcia 1
SCHEDULED: <2024-10-09 Wed>
#+INCLUDE: l/00_org_c.org
#+INCLUDE: l/10_wprowadzenie.org

* Zajęcia 2
SCHEDULED: <2024-10-16 Wed>
#+INCLUDE: l/20_nazwy.org
#+INCLUDE: l/21_stosunki.org

* Zajęcia 3
SCHEDULED: <2024-10-23 Wed>
#+INCLUDE: l/22_definicje.org
#+INCLUDE: l/23_podzial.org

** Worki ze złotymi monetami :zagadka:
Jest 100 worków z monetami. W 99 z nich są monety ze złota, ważące 20 g. W jednym z nich są monety fałszywe, ważące 19 gramów. W każdym z worków, jest nieco inna liczba monet. Monety złote i monety fałszywe nie różnią się niczym oprócz wagi. Dysponujesz wagą elektroniczną (nieskończenie dokładną), której możesz użyć tylko raz. Znajdź worek z fałszywkami.

* Zajęcia 4
SCHEDULED: <2024-10-30 Wed>
** Do przeczytania
Z podręcznika Z. Ziembińskiego przeczytaj *rozdział V*.

** Zdanie
+ Zdanie to wyrażenie stwierdzające, że jest tak a tak. Problem jednoznaczności wypowiedzi.
+ Przykłady wyrażeń niebędących zdaniami w sensie logicznym, ale będących zdaniami w sensie gramatycznym: /Zapal światło. W razie niebezpieczeństwa zbij szybę./
+ Zdarzenia i stany rzeczy.
  - Zdarzenie: rzecz lub osoba wykazywała w danym momencie własność X a w innym momencie jej nie wykazywała.
  - Stan rzeczy: rzecz lub osoba wykazywała od momentu A do momentu B jakąś własność.
+ Zdanie prawdziwe - opisuje rzeczywistość tak, jak się ona ma. Nie można wolą, teorią ani poglądem zmienić wartości prawdziwościowej zdania.
  - Czy może być zdanie prawdziwe dla kogoś?
+ Prawdziwość wynikająca z sensu użytych w nich słów; zdanie analityczne.
+ Fałszywość wynikająca z sensu słów; zdanie wewnętrznie kontradyktoryczne.
+ Zdania syntetyczne - nie da się poznać ich wartości logicznej za pomocą sensu zawartych w nich słów.
+ Zdanie niezupełne:
  - np.: „Deszcz jest pożyteczny.” - nie wiadomo dla kogo jest on pożyteczny
  - można uzupełniać je w języku potocznym kontekstem wypowiedzi

** Do przeczytania
Z podręcznika Z. Ziembińskiego przeczytaj *rozdział VI*.

* Zajęcia 5
SCHEDULED: <2024-11-06 Wed>
** Funktory prawdziwościowe
*** Wartości logiczne funktorów prawdziwościowych

| p | q | \sim{}p | p \vee q | p \cdot q | p \sup q | p \perp q | p \equiv q | p \downarrow q |
|---+---+----+-------+-------+-------+-------+-------+-------|
| 0 | 0 |  1 |     0 |     0 |     1 |     0 |     1 |     1 |
| 0 | 1 |  1 |     1 |     0 |     1 |     1 |     0 |     0 |
| 1 | 0 |  0 |     1 |     0 |     0 |     1 |     0 |     0 |
| 1 | 1 |  0 |     1 |     1 |     1 |     0 |     1 |     0 |

#+BEGIN_VERSE
Negacja:
Nieprawda, że na trawniku leży śnieg.
         \sim            p
         1            0
         0            1

Alternatywa nierozłączna:
Na trawniku leży śnieg lub jest lato.
        p                 \vee        q
        1                   1         0
        0                   1          1
        1                   1          1
        0                   0          0

Koniunkcja:
Pada deszcz i ulica jest mokra.
      p        \cdot         q
      1        1         1
      0        0         0
      1        0         0
      0        0         1

Alternatywa rozłączna:
Pójdziemy na lody albo pójdziemy do kina.
           p           \perp             q
           0           0             0
           0           1             1
           1           1             0
           1           0             1

Implikacja:
Jeżeli pada deszcz to ulica jest mokra.
           p        \sup           q 
           1        1           1
           0        1           0
           1        0           0
           0        1           1

Jeżeli (mam w kieszeni pierścień) to (koronawirus mutuje szybciej niż przeciętny wirus).
                     p                   \sup               q
                     0                   1               1
                     1                   1               1
                     0                   1               0
                     1                   0               0

Równoważność:
Wtedy i tylko wtedy gdy pada deszcz to ulica jest mokra.
             p        \equiv               q
             1        1               1
             0        1               0
             1        0               0
             0        0               1  

Binegacja:
Ani nie pada deszcz ani nie pochodzę z Marsa.
              p         \downarrow                  q
              0         1                   0
              1         0                   0
              0         0                   1
              1         0                   1
#+END_VERSE

*** Podstawowe zasady myślenia

- /T1: \sim (p \cdot \sim{}p)/ : zasada sprzeczności
- /T2: p \vee \sim(p)/ : zasada wyłączonego środka
- /T3: p \equiv \sim ( \sim p )/ : zasada podwójnego zaprzeczenia

*** Definicja implikacji przy pomocy alternatywy i negacji
p \sup q \equiv (\sim p) \vee q
1   1    1      0       1
1   0    0      0       0
0   1    1      1       1
0   1    0      1       1

*** Definicja implikacji przy pomocy koniunkcji i negacji
p \sup q \equiv \sim ( p \cdot \sim q )

*** Przykłady
 - Jeżeli Ateny są stolicą Polski to Uniwersytet Łódzki ma siedzibę w Berlinie:
   1
 - Jeżeli Ateny są stolicą Polski to Robert Lewandowski jest piłkarzem: 1
 - Jeżeli Ateny są stolicą Polski to mam w kieszeni chusteczkę: 1
 - Jeżeli Warszawa jest stolicą Polski to Księżyc jest zrobiony z sera: 0
 - Jeżeli Warszawa jest stolicą Polski to Albert Einstein opracował teorię
   względności: 1
 - Nieprawda że ( Warszawa jest stolicą Polski i nieprawda Einstein opracował
   teorię względności): 1
 - (Nieprawda że, Warszawa jest stolicą Polski) lub Einstein opracował teorię
   względności: 1
 - Ani Ateny są stolicą Polski ani UŁ ma siedzibę w Berlinie: 1

* Zajęcia 6
SCHEDULED: <2024-11-20 Wed>
** Relacje (stosunki) pomiędzy przedmiotami
*** Wstęp

/xRy/

x R_1 y - Adam jest wyższy od Piotra

y R_2 x - Piotr jest niższy od Adama

x = y, y = z

kiwi kiwi kiwi

x R y

*** Relacje symetryczne, asymetryczne i nonsymetryczne

Jan jest małżonkiem Zofii.

Jan jest starszy od Zofii. x jest mniejszy od y, x jest większy od y, x jest brzydszy od y, x jest grubszy od y.

Jan kocha Zofię. x jest bratem y, x patrzy na y, x mówi do y.

*** Stosunek przechodni (tranzytywny), atranzytywny, nontranzytywny

- Stosunek tranzytywny: jeśli xRy i yRz to xRz.
- Stosunek atranzytywny: jeśli xRy i yRz to \sim xRz.
- Stosunek nontranzytywny: jeśli xRy i yRz to xRz \perp (\sim xRz).

- zawiera - jest tranzytywny
- jest częścią - relacja tranzytywna
- jest matką - relacja atranzytywna: x jest matką y, y jest matką z \sup x nie jest matką z
- samodzielnie wychowywać - relacja atranzytywna
- jest krewnym - relacja nontranzytywna
- jest szefem - relacja nontranzytywna
- jest pracownikiem tej samej firmy - relacja nontranzytywna
- lubi - relacja nontranzytywna
- jest przyjacielem - relacja nontranzytywna
  
*** Stosunek spójny, porządkujący, równościowy i zwrotne

Przykładowy zapis:

  - { 4, 1, 2, 3 }; R: <

  - *Stosunek spójny* zachodzi w jednym lub drugim kierunku w danej klasie przedmiotów między każdym i dowolnie wybranym przedmiotem.
    - {1, 1, 1, 1}, R: =
    - {1, 2, 3, 1}, R: =<
    - {1, 2, 3, 4}, R: <
  - *Stosunek porządkujący* pozwala ustawić przedmioty w szeregu: asymetryczny, przechodni i spójny.
    - { 4, 1, 2, 3 }, R: <
    - { Adam lat 10, Weronika lat 12, Bronisław lat 64, Kunegunda lat 102 }, R: jest starszy(a) 
  - *Stosunek zwrotny* zachodzi pomiędzy każdym elementem w danej klasie przedmiotów a nim samym:
    - { 4 , 5 , 9, 23 }, R: jest równe
  - *Stosunek równościowy*: symetryczny, przechodni i zwrotny:
    + { 4, 4, 4 } R: /jest równe/
    + { Wojtek blondyn, Kasia blondynka, Alicja blondynka, Cezary blondyn }, R: /ma taki sam kolor włosów jak/
    + { Skoda Octavia 1.9TDI, Audi A3 2.0TDI, BMW 330d }, R: /jest na takie samo paliwo jak/
    + { Adam, Franciszek, Bartek }^1 R: /być bratem/ (1 - panowie są braćmi)
      
* Zajęcia 7
SCHEDULED: <2024-11-27 Wed>
** Wypowiedzi oceniające i normy
- Wypowiedź oceniająca.
  - Rodzaje ocen
    - ocena estetyczna
    - ocena hedonistyczna
    - ocena moralna
- Preferencje.
- Globalne oceny stanu rzeczy.

- Norma postępowania.
- Normy prawne, to normy postępowania, ale należy pamiętać, że zakres nazwy norma prawna jest podrzędny zakresowi nazwy norma postępowania.
- Wypowiedź dyrektywalna.
- Pojęcie postępowania.
- Zakaz, nakaz: zakaz czynienia X to nakaz nieczynienia X; nakaz czynienia X to zakaz nieczynienia X.
  - N X \equiv Z \sim{}X
- Normy mogą być:
  1) a) generalne, b) indywidualne;
  2) a) abstrakcyjne, b) konkretne.
- Przykład normy generalnej i abstrakcyjnej: Kto zabija człowieka, podlega karze pozbawienia wolności na czas nie krótszy od lat 8, karze 25 lat pozbawienia wolności albo karze dożywotniego pozbawienia wolności - Każdemu i w każdych okolicznościach zakazuje się zabić człowieka.
- Przykład normy konkretnej i indywidualnej: Sąd Okręgowy w Warszawie … zasądza od Jana Kowalskiego kwotę 1000 zł na rzecz Adama Malinowskiego z odsetkami ustawowymi za opóźnienie…
- Przykład normy generalnej i konkretnej: Kto z uczestników wycieczki wróci dziś pierwszy do schroniska powinien rozpalić ogień.
- Przykład normy indywidualnej i abstrakcyjnej: Szeregowy Kowalski, gdy dostrzeżecie niebezpieczeństwo macie wszcząć alarm.
- Podporządkowanie normie.

- Obowiązywanie normy.
  + Uzasadnienie tetyczne;
  + uzasadnienie aksjologiczne.

* Zajęcia 8
SCHEDULED: <2024-12-04 Wed>
** Wypowiedzi modalne
- wzajemna definiowalność: /musi robić to znaczy, że nie może nie robić ; może robić to znaczy, że nie musi nie robić/
- interpretacje słów „musi” i „może”
  + interpretacja logiczna - słowo „musi” oznacza pewien związek pomiędzy zdaniami; /obwód okręgu o promieniu 1 cm musi mieć 2 pi cm/; /kwadrat musi mieć cztery boki/
  + interpretacja dynamiczna - fakt jest nieuchronny; /ciało niepodparte musi spadać/, /Żołnierze bez pożywienia muszą w końcu przegrać./
  + interpretacja aksjologiczna - aprobujemy stan A i nie godzimy się na to, aby stan przeciwny nie zachodził - /Musisz płacić podatki. Jeśli jesteś bogatszy od innych to musisz płacić wyższe podatki. Musisz przestać palić papierosy, bo osierocisz swoje dzieci./
  + interpretacja tetyczna - zrealizowanie stanu A jest nakazane normą: /W końcu będziesz musiał wydać wyrok./ /Musisz zawiadomić prokuratora o tym, że próbowano Cię przekupić. Musisz płacić podatki./
  + interpretacja psychologiczna - jesteśmy silnie przeświadczeni, że A: /musi być A/.
- ćwiczenie:
  + Żołnierz musi nosić mundur na służbie.
  + W terenie zabudowanym musisz jechać z prędkością poniżej 50 km/h.
  + Sędzia może wydać wyrok a prokurator nie może wydać wyroku.
  + Warszawa musi być stolicą Polski.
  + Łódź musi być stolicą Polski.
  + Adam może wyjść z domu. = Adam nie musi nie wychodzić z domu.
  + Lecący samolot, w którym skończyło się paliwo, musi spaść.
- Modalności
  + zdanie asertoryczne: Jest tak a tak. /Na pasie startowym stoi samolot. Łódź jest położona w centralnej Polsce./
  + zdanie apodyktyczne: Musi być tak a tak. /Musisz nauczyć się logiki./
  + zdanie problematyczne: Może być tak a tak. /Logiki możesz uczyć się nawet w okresie świątecznym. Jutro możliwe są opady deszczu./
- Możliwość jednostronna i możliwość dwustronna
  + Kwadrat musi mieć cztery boki. Czy kwadrat może mieć cztery boki?
  + Kwadrat może mieć cztery boki. Adam może wyjść z domu. Rzecznikiem Praw Obywatelskich może być obywatel polski wyróżniający się wiedzą prawniczą, doświadczeniem zawodowym oraz wysokim autorytetem ze względu na swe walory moralne i wrażliwość społeczną.
  + Jest możliwe zjeść kawałek pizzy. Jan może zjeść kawałek pizzy.
  + Jest możliwe, że Lech Wałęsa był prezydentem Polski.
  + Ziemia może być trzecią planetą od Słońca (możliwość jednostronna). Każdy dorosły Polak może głosować w wyborach prezydenckich (możliwość dwustronna - może przecież także nie głosować).
- Modalności normatywne
  + nakaz /osoba x musi postąpić w określony sposób/
  + zakaz /osoba x nie może postąpić w określony sposób/
  + dozwolenie /brak zakazu/
  + fakultatywność /brak nakazu/
  + indyferentność - dozwolony i fakultatywny
  + obowiązek - zakaz albo nakaz

Milczenie norm a zachowanie człowieka.

Milczenie na temat X oznacza zakaz; a zatem zakazane jest też ~X: prowadzi więc to do sprzeczności, tj. X oraz ~X są jednocześnie zakazane. 

** Do przeczytania
Z podręcznika Z. Ziembińskiego przeczytaj *Rozdział 10*.
* Zajęcia 9
SCHEDULED: <2024-12-11 Wed>
** Pytania i odpowiedzi

- Pytanie: nie jest zdaniem w sensie logicznym; pytania na serio, pytania retoryczne
- założenia pytania i pytania niewłaściwie postawione
  + Czy nadal bijesz swoją siostrę? Założenia: masz siostrę, kiedyś biłeś siostrę; jeżeli adresat pytania nie miał nigdy siostry to jest to /pytanie źle postawione/
- sposób zadawania pytań:
  + partykuła pytajna: kto, kiedy, jak, gdzie
  + otwarte i zamknięte
  + pytania do rozstrzygnięcia: Czy najwyższy w klasie jest Wojtek czy Bartek?
  + pytania do uzupełnienia: Kto zjadł moją pizzę?
  + niewiadoma pytania
  + zakres niewiadomej pytania - klasa elementów, których nazwy można wstawić w miejsce niewiadomej pytania
  + pytania sugestywne/sugerujące i podchwytliwe:
    - Czy uciekający mężczyzna miał na sobie czerwoną kurtkę? (gdy nie wiemy czy adresat pytania widział aby ktokolwiek uciekał)
    - Czy pozwany zgodzi się zapłacić 100 zł tytułem zwrotu pożyczki? (gdy pozew opiewa na większą kwotę a pozwany zaprzecza istnieniu pożyczki)
- odpowiedzi:
  + właściwa / niewłaściwa (nie jest tożsame z prawidłowością odpowiedzi): Kto był najwybitniejszym polskim poetą? Najwybitniejszym polskim poetą był William Shakspeare.
  + całkowite / częściowe:
    - Jakiego koloru są mundury aspirantów w Policji? Mundury aspirantów w Policji są koloru niebieskiego (odpowiedź całkowita wprost). Wszystkie mundury w Policji są niebieskie (odpowiedź całkowita nie wprost).
    - Kto pana pobił? Pobił mnie mężczyzna w płaszczu i czapce z dwoma daszkami (odpowiedź częściowa).
** Do przeczytania
Z podręcznika Z. Ziembińskiego przeczytaj *Rozdział 11*.

* Zajęcia 10
SCHEDULED: <2024-12-18 Wed>
** Nieporozumienia
- wieloznaczność słów:
  + Każdy lubiący jeść pączki, lubi chodzić do cukierni. Łoś lubi jeść pączki. A więc, łoś lubi chodzić do cukierni.
  + znaczenie aktualne i znaczenie potencjalne: Czy Tadek gra w brydża?
- błąd ekwiwokacji: użycie tego samego słowa w różnych znaczeniach; szczególne znaczenie w przypadku mowy prawniczej
- wieloznaczność wypowiedzi złożonej: Nigdy nie można zrobić zbyt wiele dla ludzi starych i chorych. 
- skróty myślowe: Mniej znaczy więcej.
** Uzasadnianie bezpośrednie twierdzeń
- w jaki sposób można uznać zdanie za prawdziwe? /Postulat racji dostatecznej/ - za prawdziwe należy uznać jedynie takie zdanie, dla którego da się uzyskać należyte uzasadnienie
  + dla zdań syntetycznych - uzasadnienie opiera się na spostrzeżeniach
  + dla zdań analitycznych - uzasadnienie opiera się na regułach znaczeniowych danego języka
  + uzasadnienia pośrednie pochodzą z wnioskowania z innych zdań przyjętych uprzednio za prawdziwe
- spostrzeżenia: zewnętrzne i wewnętrzne; problem iluzji (https://www.youtube.com/watch?v=BzNzgsAE4F0)
- spostrzeżenia:
  + przypadkowe,
  + obserwacja,
  + pomiar,
  + eksperyment
** Dedukcja a indukcja
   - dedukcja jako wnioskowanie niezawodne
   - indukcja jako wnioskowanie zawodne 
** Do przeczytania
Z podręcznika Z. Ziembińskiego przeczytaj *Rozdział 12 i 13*.
* Zajęcia 11 
SCHEDULED: <2025-01-08 Wed>
** Dedukcja
* Zajęcia 12 
SCHEDULED: <2024-12-11 Wed>
** Indukcja

Indyk filozof miał hipotezę "Człowiek jest po to, aby służyć indykom." Nastąpiło aż 1000 obserwacji potwierdzający tę hipotezę. Dnia 1001 człowiek upiekł indyka.

- Indukcja enumeracyjna:
  - S_1 jest P,
  - S_2 jest P,
  - S_3 jest P,
  - S_4 jest P,
  - S_n jest P,
  - Każde S jest P.
  - S_n - dzień, P dzień mający cechę X (np. dzień w którym człowiek służy indykowi)
- Indukcja zupełna i niezupełna.
- Indukcja eliminacyjna:
  a. kanon jednej zgodności: O_1: A, B, C, Z; O_2: C, D, E, Z; O_3: C, F, G, Z.
  b. kanon jednej różnicy: 
     - O_1: A, B, C, Z;
     - O_2: B, C, Z;
     - O_3: A, C, Z;
     - O_4: A, B, ~Z.
  c. kanon zmian towarzyszących:
     - kuchenka gazowa ma palniki od 1 do 4 i 4 kurki (A…D)
     - zadanie: ustal który kurek steruje palnikiem nr 2
     - obserwacje:
       1) kurek A w poz. 50%, brak płomienia
       2) kurek A w poz. 100%, brak płomienia
       3) kurek B w poz. 50%, brak płomienia
       4) kurek B w poz. 100%, brak płomienia
       5) kurek C w poz. 50%, mały płomień
       6) kurek C w poz. 100%, duży płomień
       7) kurek D w poz. 50%, brak płomienia
       8) kurek D w poz. 100%, brak płomienia
     - wniosek: prawdopodobnie kurek C steruje płomieniem palnika nr 2.

** Prawdopodobieństwo
** Do przeczytania
Z podręcznika Z. Ziembińskiego przeczytaj *Rozdział 15*.

* Zajęcia 13
SCHEDULED: <2025-01-22 Wed>
Powtórzenie.

* Zajęcia 14
SCHEDULED: <2025-01-29 Wed>
Zaliczenie.

* Bonus track
Spotykamy się online i gramy w grę uczącą nas funktorów prawdziwościowych.
