** Zagadnienia organizacyjne - logika (ćwiczenia)
*** Warunki zaliczenia przedmiotu
1. Prezentacje: 50%
2. Aktywność: 50%
3. Obecność.

*** Skala ocen
#+include: ../g/skala.org

*** Obecność
   * Lista obecności dostępna jest na: https://forms.office.com/e/rDKUfQhKgN
   * Zawsze pamiętaj o uzupełnieniu listy obecności. Niewypełnienie formularza w dniu zajęć ma taki sam skutek jak milczenie przy ustnym sprawdzaniu obecności.

#+include: ../g/prezentacje.org :minlevel 3

*** Literatura
a) literatura obowiązkowa:
   - Z. Ziembiński, /Logika Praktyczna/, Warszawa 2004 (albo inne wydanie).
b) literatura uzupełniająca:
   - T. Bekrycht, /Logiczne podstawy prawoznawstwa/, Warszawa 2010,
   https://www.academia.edu/21615638/LOGIKA_skrypt_Bekrycht.
   - J. Stelmach, B. Brożek, /Metody Prawnicze/, rozdziały I, II, III pkt.
   1-2.
   - J. Wajszczyk, /Jestem więc myślę/, Warszawa 2003.

*** Przerwy
5-10 minut w połowie zajęć albo w ostatniej części zajęć.

*** Nieobecności
Dopuszczalne są dwie nieobecności. Każda nieobecność ponad dwie nieobecności obniża ocenę końcową o pół stopnia.
