** Wnioskowania niededukcyjne
*** Redukcja
Forma:
- przesłanka formułowana: /p/
- przesłanka entymematyczna: /q \rarr p/
- wniosek: /q/

Z tego, że wiem, że ulica jest morka (p) oraz wiem, że jeżeli pada desz to ulica jest mokra (q \rarr p) wnioskuję, że padał deszcz (q).

*** Indukcja
Indyk filozof miał hipotezę "Człowiek jest po to, aby służyć indykom." Nastąpiło aż 1000 obserwacji potwierdzających tę hipotezę. Dnia 1001 człowiek upiekł indyka.

- Indukcja enumeracyjna:
  - S_1 jest P,
  - S_2 jest P,
  - S_3 jest P,
  - S_4 jest P,
  - S_n jest P,
  - Każde S jest P.
  - S_n - dzień, P dzień mający cechę X (np. dzień w którym człowiek służy indykowi)
- Indukcja zupełna i niezupełna.
- Indukcja eliminacyjna:
  a. kanon jednej zgodności:
     - O_1: A, B, C, Z;
     - O_2: C, D, E, Z;
     - O_3: C, F, G, Z.
  b. kanon jednej różnicy:
     - O_1: A, B, C, Z;
     - O_2: B, C, Z;
     - O_3: A, C, Z;
     - O_4: A, B, ~Z.
  c. kanon zmian towarzyszących:
     - kuchenka gazowa ma palniki od 1 do 4 i 4 kurki (A…D)
     - zadanie: ustal który kurek steruje palnikiem nr 2
     - obserwacje:
       1) kurek A w poz. 50%, brak płomienia
       2) kurek A w poz. 100%, brak płomienia
       3) kurek B w poz. 50%, brak płomienia
       4) kurek B w poz. 100%, brak płomienia
       5) kurek C w poz. 50%, mały płomień
       6) kurek C w poz. 100%, duży płomień
       7) kurek D w poz. 50%, brak płomienia
       8) kurek D w poz. 100%, brak płomienia
     - wniosek: prawdopodobnie kurek C steruje płomieniem palnika nr 2.
