** Nieporozumienia
Ziembiński: Rozdział 12

*** Wieloznaczność słów
Słowa są wieloznaczne, ale… przecież mamy kontekst.

Przykłady:
- /Podaj mi dzban./
- /Sam jesteś dzban!/

*** Pomieszanie supozycji
/Kajet jest pochodzenia francuskiego./

*** Znaczenie aktualne i znaczenie potencjalne
Czy Tadek gra w brydża?

*** Słowa okazjonalne
- wtedy
- on
- tam

Co zrobić , gdy świadek odopowiada na pytanie: „On to wtedy tam zrobił.”

*** Ekwiwokacje. Spory słowne

Błąd ekwiwokacji: użycie tego samego słowa w różnych znaczeniach.

Przykład:
- Każdy metal jest pierwiaskiem. Mosiądz jest metalem. A zatem mosiądz jest pierwiastkiem.
- Każdy ssak lubiący jeść pączki, lubi chodzić do cukierni. Łoś lubi jeść pączki. A więc, łoś lubi chodzić do cukierni.

Logomachia (spór słowny) - spory wnikające z nieuzgodnienia pomiędzy dyskutantami o jakim znaczeniu danego słowa mówią. Przykład:

- Dyskusja na temat czy każdy człowiek żyjący w zgodzie z naturą jest szczęśliwy.
- Dyskusja na temat czy autorytaryzm jest dobry dla gospodarki.

*** Wieloznaczność wypowiedzi złożonej
Nigdy nie można zrobić zbyt wiele dla ludzi starych i chorych.
- znaczenie dosłowne i niedosłowne: /Człowiek człowiekowi wilkiem./

*** Amfibologia
Wypowiedź wieloznaczna ze względu na składnię:
- /Paweł powiedział swojej koleżance, że ona jest niemądra./
- /Pozwany ma płacić powodowi 90 złotych renty alimentacyjnej łącznie z zasiłkiem rodzinnym./

*** Znaczenie dosłowne i niedosłowne
- /Ty jesz ananasy, a mnie na chleb nie starcza. Nieprawda, ja nie lubię ananansów, a ciebie stać na 0.8 kg chleba dziennie!/
- /Mniej znaczy więcej./
